### 김프 분석

In [1]:
import pandas as pd
df = pd.read_csv('DATA/2023_BTC-KRW_upbit-binance.csv',index_col=0)
df

,Open time,Upbit,Binance,diff,diff_percentage
0,2023-01-01 00:00:00,21064000.0,2.095529e+07,108712.926,0.518785
1,2023-01-01 00:05:00,21040000.0,2.094425e+07,95751.109,0.457171
2,2023-01-01 00:10:00,21012000.0,2.093667e+07,75329.563,0.359797
3,2023-01-01 00:15:00,21010000.0,2.095473e+07,55270.538,0.263762
4,2023-01-01 00:20:00,21048000.0,2.095549e+07,92510.158,0.441460
...,...,...,...,...,...
105115,2023-12-31 23:35:00,57070000.0,5.445278e+07,2617219.660,4.806402
105116,2023-12-31 23:40:00,57072000.0,5.446566e+07,2606338.554,4.785288
105117,2023-12-31 23:45:00,57080000.0,5.450272e+07,2577281.198,4.728720
105118,2023-12-31 23:50:00,57018000.0,5.444118e+07,2576824.260,4.733227
105119,2023-12-31 23:55:00,57047000.0,5.452045e+07,2526551.948,4.634136

In [2]:
df_PM = df.copy()
df_PM.loc[df_PM['diff'] < 0, 'sgn'] = '-'
df_PM.loc[df_PM['diff'] >= 0, 'sgn'] = '+'
df_PM

,Open time,Upbit,Binance,diff,diff_percentage,sgn
0,2023-01-01 00:00:00,21064000.0,2.095529e+07,108712.926,0.518785,+
1,2023-01-01 00:05:00,21040000.0,2.094425e+07,95751.109,0.457171,+
2,2023-01-01 00:10:00,21012000.0,2.093667e+07,75329.563,0.359797,+
3,2023-01-01 00:15:00,21010000.0,2.095473e+07,55270.538,0.263762,+
4,2023-01-01 00:20:00,21048000.0,2.095549e+07,92510.158,0.441460,+
...,...,...,...,...,...,...
105115,2023-12-31 23:35:00,57070000.0,5.445278e+07,2617219.660,4.806402,+
105116,2023-12-31 23:40:00,57072000.0,5.446566e+07,2606338.554,4.785288,+
105117,2023-12-31 23:45:00,57080000.0,5.450272e+07,2577281.198,4.728720,+
105118,2023-12-31 23:50:00,57018000.0,5.444118e+07,2576824.260,4.733227,+
105119,2023-12-31 23:55:00,57047000.0,5.452045e+07,2526551.948,4.634136,+

In [3]:
df_PM['diff_percentage'].describe()

count    105104.000000
mean          1.673043
std           1.317540
min          -3.866144
25%           0.732531
50%           1.523371
75%           2.477708
max          10.207584
Name: diff_percentage, dtype: float64

##### 업비트, 바이낸스 매수, 매도 

- 역프 꼈을 때 업비트에서 매수, 바이낸스에서 매도
- 김프 꼈을 때 업비트에서 매도, 바이낸스에서 매수

In [104]:
upbit_trade_info_all = list()
sgn_stat = 'buy'

for i in range(len(df_PM)):
    if sgn_stat =='buy' and df_PM.loc[i]['diff_percentage']<-0.5:
        trade_info = dict()
        buy_price = df_PM.loc[i]['Upbit']
        sgn_stat='sell'
        trade_info['buy'] = buy_price

    elif sgn_stat =='sell' and df_PM.loc[i]['diff_percentage']>0.5:
        sell_price = df_PM.loc[i]['Upbit']
        sgn_stat = 'buy'
        trade_info['sell'] = sell_price
        upbit_trade_info_all.append(trade_info)
    else:
        continue
upbit_trade_info_all

[{'buy': 21705000.0, 'sell': 21657000.0},
 {'buy': 25816000.0, 'sell': 26271000.0},
 {'buy': 31500000.0, 'sell': 31845000.0},
 {'buy': 29256000.0, 'sell': 31670000.0},
 {'buy': 39928000.0, 'sell': 39644000.0},
 {'buy': 39578000.0, 'sell': 38841000.0},
 {'buy': 39708000.0, 'sell': 37948000.0},
 {'buy': 38703000.0, 'sell': 38184000.0},
 {'buy': 39597000.0, 'sell': 39900000.0},
 {'buy': 37554000.0, 'sell': 37258000.0},
 {'buy': 40389000.0, 'sell': 45879000.0},
 {'buy': 45992000.0, 'sell': 46353000.0}]

In [105]:
df_upbit_trade_info = pd.DataFrame(upbit_trade_info_all)
df_upbit_trade_info['profit'] = df_upbit_trade_info['sell'] - df_upbit_trade_info['buy']
df_upbit_trade_info

           buy        sell     profit
0   21705000.0  21657000.0   -48000.0
1   25816000.0  26271000.0   455000.0
2   31500000.0  31845000.0   345000.0
3   29256000.0  31670000.0  2414000.0
4   39928000.0  39644000.0  -284000.0
5   39578000.0  38841000.0  -737000.0
6   39708000.0  37948000.0 -1760000.0
7   38703000.0  38184000.0  -519000.0
8   39597000.0  39900000.0   303000.0
9   37554000.0  37258000.0  -296000.0
10  40389000.0  45879000.0  5490000.0
11  45992000.0  46353000.0   361000.0

In [106]:
df_upbit_trade_info['profit_rate'] = df_upbit_trade_info['profit']/df_upbit_trade_info['sell']*100
df_upbit_trade_info['profit_rate'].mean()

1.1929210962097778

In [123]:
df_PM['diff_percentage'].describe()

count    105104.000000
mean          1.673043
std           1.317540
min          -3.866144
25%           0.732531
50%           1.523371
75%           2.477708
max          10.207584
Name: diff_percentage, dtype: float64

In [130]:
# sgn + 일 때 upbit 매도, binance 매수
# sgn - 일 때 binance 매도, upbit 매수

trade_info_all = list()
sgn_stat = 'buy'

for i in range(len(df_PM)):
    if sgn_stat =='buy' and df_PM.loc[i]['diff_percentage']<0:
        trade_info = dict()
        buy_price = df_PM.loc[i]['Binance']
        sgn_stat='sell'
        trade_info['buy'] = buy_price
    
    elif sgn_stat =='sell' and df_PM.loc[i]['diff_percentage']>=0:
        sell_price = df_PM.loc[i]['Binance']
        sgn_stat = 'buy'
        trade_info['sell'] = sell_price
        trade_info_all.append(trade_info)
    else:
        continue
trade_info_all

binance_trade_info = pd.DataFrame(trade_info_all)
binance_trade_info['profit'] = binance_trade_info['sell'] - binance_trade_info['buy']

binance_trade_info['profit_rate'] = binance_trade_info['profit']/binance_trade_info['sell']*100
binance_trade_info['profit_rate'].mean()

-0.021085464051417264

In [131]:
binance_trade_info

              buy          sell      profit  profit_rate
0    2.143332e+07  2.145213e+07   18814.572     0.087705
1    2.144065e+07  2.144571e+07    5060.559     0.023597
2    2.145482e+07  2.144693e+07   -7890.393    -0.036790
3    2.144516e+07  2.145103e+07    5876.367     0.027394
4    2.144833e+07  2.144795e+07    -382.410    -0.001783
..            ...           ...         ...          ...
384  4.715523e+07  4.711685e+07  -38375.224    -0.081447
385  4.710406e+07  4.704930e+07  -54762.264    -0.116393
386  4.738849e+07  4.720350e+07 -184985.504    -0.391889
387  4.715294e+07  4.713355e+07  -19395.808    -0.041151
388  4.708471e+07  4.704789e+07  -36817.112    -0.078255

[389 rows x 4 columns]

In [ ]:
len(binance_trade_info)

389

In [120]:
binance_trade_info

              buy          sell      profit  profit_rate
0    2.143332e+07  2.145213e+07   18814.572     0.087705
1    2.144065e+07  2.144571e+07    5060.559     0.023597
2    2.145482e+07  2.144693e+07   -7890.393    -0.036790
3    2.144516e+07  2.145103e+07    5876.367     0.027394
4    2.144833e+07  2.144795e+07    -382.410    -0.001783
..            ...           ...         ...          ...
384  4.715523e+07  4.711685e+07  -38375.224    -0.081447
385  4.710406e+07  4.704930e+07  -54762.264    -0.116393
386  4.738849e+07  4.720350e+07 -184985.504    -0.391889
387  4.715294e+07  4.713355e+07  -19395.808    -0.041151
388  4.708471e+07  4.704789e+07  -36817.112    -0.078255

[389 rows x 4 columns]

In [134]:
binance_trade_info['profit_rate'].describe()

count    389.000000
mean      -0.021085
std        0.769745
min       -2.262391
25%       -0.111229
50%       -0.021247
75%        0.054552
max       11.881977
Name: profit_rate, dtype: float64

In [132]:
balance = 1
for i in binance_trade_info['profit_rate'] :
    balance += balance*(i/100)
balance

0.9111863571744563

In [122]:
balance = 0.5
for i in df_upbit_trade_info['profit_rate'] :
    balance += balance*(i/100)
balance

0.570576459397093

매수 매도를 하는데 있어 결정적인 지표는 아니더라도 거래소 선택에 있어서 도움

In [136]:
df_PM

,Open time,Upbit,Binance,diff,diff_percentage,sgn
0,2023-01-01 00:00:00,21064000.0,2.095529e+07,108712.926,0.518785,+
1,2023-01-01 00:05:00,21040000.0,2.094425e+07,95751.109,0.457171,+
2,2023-01-01 00:10:00,21012000.0,2.093667e+07,75329.563,0.359797,+
3,2023-01-01 00:15:00,21010000.0,2.095473e+07,55270.538,0.263762,+
4,2023-01-01 00:20:00,21048000.0,2.095549e+07,92510.158,0.441460,+
...,...,...,...,...,...,...
105115,2023-12-31 23:35:00,57070000.0,5.445278e+07,2617219.660,4.806402,+
105116,2023-12-31 23:40:00,57072000.0,5.446566e+07,2606338.554,4.785288,+
105117,2023-12-31 23:45:00,57080000.0,5.450272e+07,2577281.198,4.728720,+
105118,2023-12-31 23:50:00,57018000.0,5.444118e+07,2576824.260,4.733227,+
105119,2023-12-31 23:55:00,57047000.0,5.452045e+07,2526551.948,4.634136,+

In [ ]:
!pip install